sudo: required
branches:
  only:
    - graphql-api-functional-coverage
dist: trusty
group: edge
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
  hosts:
      - magento2.travis
services:
  - rabbitmq
  - elasticsearch
language: php
php:
  - 7.2
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - MAGENTO_HOST_NAME="magento2.travis"
  matrix:
    - TEST_SUITE=graphql-api-functional-coverage
matrix:
  exclude:
    - php: 7.1
      env: TEST_SUITE=graphql-api-functional-coverage
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.nvm
    - $HOME/node_modules
    - $HOME/yarn.lock
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.0/elasticsearch-2.3.0.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.0.deb && sudo service elasticsearch restart
  - ./dev/travis/before_install.sh
install: composer install --no-interaction
before_script: ./dev/travis/before_script.sh
script:
  - if [ $TEST_SUITE == "graphql-api-functional-coverage" ]; then phpunit -c dev/tests/api-functional; fi
